export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS";
export const CONTACTS_ERROR = "CONTACTS_ERROR";

export const CREATE_CONTACTS_LOADING = "CREATE_CONTACTS_LOADING";
export const CREATE_CONTACTS_SUCCESS = "CREATE_CONTACTS_SUCCESS";
export const CREATE_CONTACTS_ERROR = "CREATE_CONTACTS_ERROR";

export const EDIT_CONTACT_LOADING = "EDIT_CONTACT_LOADING";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_ERROR = "EDIT_CONTACT_ERROR";

export const DELETE_CONTACT_LOADING = "DELETE_CONTACT_LOADING";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";

export const OPEN_CREATE_CONTACTS_MODAL = "OPEN_CREATE_CONTACTS_MODAL";
export const CLOSE_CREATE_CONTACTS_MODAL = "CLOSE_CREATE_CONTACTS_MODAL";

export const OPEN_EDIT_CONTACTS_MODAL = "OPEN_EDIT_CONTACTS_MODAL";
export const CLOSE_EDIT_CONTACTS_MODAL = "CLOSE_EDIT_CONTACTS_MODAL";

export const ADD_REMOVE_FAVOURITE_LOADING = "ADD_REMOVE_FAVOURITE_LOADING";
export const ADD_REMOVE_FAVOURITE_SUCCESS = "ADD_REMOVE_FAVOURITE_SUCCESS";
export const ADD_REMOVE_FAVOURITE_ERROR = "ADD_REMOVE_FAVOURITE_ERROR";

export const SELECT_CONTACT = "SELECT_CONTACT";

export const USER_LOGOUT = "USER_LOGOUT";

export const SEARCH_CONTACT = "SEARCH_CONTACT";
